keycloak:
  realm: hermes
  resource: internal-frontend
  principal-attribute: preferred_username
spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
server:
  port: 8082
logging:
    level:
      root: info