keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: hermes
  resource: internal-frontend
  public-client: true
  principal-attribute: preferred_username


server:
  port: 8083
logging:
    level:
      root: info